remote_theme: jekyll/minima
title: Machine Learning Production Systems
description: A machine learning publication by Robert Crowe (Google), Hannes Hapke (Digits), Emily Caveness (Google) and Di Zhu (Google)
minima:
  skin: dark
